# Generated by Django 3.2 on 2022-01-27 18:17

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validate_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(blank=True, choices=[('accounting', 'Accounting'), ('owner', 'Owner'), ('manager', 'Manager'), ('hr', 'Human Resources'), ('customer', 'Customer')], default='customer', max_length=20, null=True)),
                ('raw_password', models.CharField(max_length=255)),
                ('reset_password_code', models.CharField(blank=True, max_length=6, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, 'auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
