# Generated by Django 3.2 on 2022-01-27 18:17

from django.db import migrations, models
import django_lifecycle.mixins


def create_setup(apps, schema_editor):
    from apps.main.models import Setup
    Setup.objects.create()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_register', models.BooleanField(default=False)),
                ('disable_user_when_register', models.BooleanField(default=True)),
                ('http_server_on', models.BooleanField(default=True)),
                ('ws_server_on', models.BooleanField(default=True)),
                ('twilio_key', models.CharField(blank=True, max_length=30, null=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=50, null=True)),
                ('twilio_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email_host', models.CharField(blank=True, max_length=50, null=True)),
                ('email_host_user', models.CharField(blank=True, max_length=50, null=True)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_public_key', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_private_key', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_link_url', models.URLField(blank=True, null=True)),
                ('frontend_url', models.URLField(blank=True, null=True)),
                ('backend_url', models.URLField(blank=True, null=True)),
                ('test_mode', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setup',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=15)),
                ('sms', models.TextField()),
                ('success', models.BooleanField(null=True)),
                ('source', models.CharField(max_length=20)),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Sms',
                'verbose_name_plural': 'Sms',
            },
        ),
        migrations.RunPython(
            create_setup
        ),
    ]
